name: Block PRs with "build error" label
on:
  pull_request:
    types:
      - synchronize
      - opened

jobs:
  block-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Labels
        run: |
          if [[ "$(echo ${{ github.event.pull_request.labels.*.name }})" == *"build error"* ]]; then
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}