
name: Java CI with Maven

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v3.5.3
    - name: Set up JDK 19 Temurin
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '19'
    
    - name: Cache Maven packages
      uses: actions/cache@v3.3.1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build and analyze
      env:
        GITHUB_TOKEN: ${{ secrets.QUALITY_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=upa-io_quarkus-microservices-chassis
    
    - name: Build with Maven
      if: ${{ success() }}
      run: mvn -B package --file pom.xml -DskipTests

    - name: Add label build successful to PR
      if: ${{ success() }}
      uses: actions/github-script@v6.4.1
      with:
        github-token: ${{ secrets.PR_ADD_LABEL_TOKEN }}
        script: |
          const { data: pullRequest } = await github.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.payload.pull_request.number
          });
          const labels = pullRequest.labels.map(label => label.name);
          if (labels.includes('build successful')) {
            await github.issues.removeLabel({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.payload.pull_request.number,
            name: 'build error'
            });
          }
          await github.issues.addLabels({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.payload.pull_request.number,
            labels: ['build successful']
          });
    - name: Add label build error to PR
      if: ${{ failure() }}
      uses: actions/github-script@v6.4.1
      with:
        github-token: ${{ secrets.PR_ADD_LABEL_TOKEN }}
        script: |
          const { data: pullRequest } = await github.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.payload.pull_request.number
          });
          const labels = pullRequest.labels.map(label => label.name);
          if (labels.includes('build successful')) {
            await github.issues.removeLabel({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.payload.pull_request.number,
            name: 'build successful'
            });
          }
          await github.issues.addLabels({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.payload.pull_request.number,
            labels: ['build error']
          });

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@v3.0.2
