# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v3.5.3
    - name: Set up JDK 19 Temurin
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '19'
    
    - name: Cache Maven packages
      uses: actions/cache@v3.3.1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Get version from pom.xml
      id: get-version
      run: |
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "version=${VERSION}" >> $GITHUB_ENV

    - name: Build and analyze
      env:
        GITHUB_TOKEN: ${{ secrets.QUALITY_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=upa-io_quarkus-microservices-chassis
    
    - name: Build with Maven
      if: ${{ success() }}
      run: mvn -B package --file pom.xml -DskipTests

    - name: Set up QEMU
      if: ${{ success() }}
      uses: docker/setup-qemu-action@v2.2.0

    - name: Set up Docker Buildx
      if: ${{ success() }}
      uses: docker/setup-buildx-action@v2.7.0

    - name: Login to GitHub Container Registry
      if: ${{ success() }}
      uses: docker/login-action@v2.2.0
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.REGISTRY_TOKEN }}

    - name: Build and push
      if: ${{ success() }}
      uses: docker/build-push-action@v4.1.1
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ghcr.io/user/app:latest
          ghcr.io/user/app:1.0.0-SNAPSHOT

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@v3.0.2
