
name: Java CI with Maven

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v3.5.3
    - name: Set up JDK 19 Temurin
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '19'
    
    - name: Cache Maven packages
      uses: actions/cache@v3.3.1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build and analyze
      env:
        GITHUB_TOKEN: ${{ secrets.QUALITY_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=upa-io_quarkus-microservices-chassis
    
    - name: Build with Maven
      if: ${{ success() }}
      run: mvn -B package --file pom.xml -DskipTests

    - name: Resolve build successful and add build error label
      if: ${{ failure() && contains(github.event.pull_request.labels.*.name, 'build successful') }}
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.removeLabel({
            issue_number: context.payload.pull_request.number,
             owner: context.repo.owner,
             repo: context.repo.repo,
             name: 'build successful'
           });
          
           github.rest.issues.addLabels({
             issue_number: context.payload.pull_request.number,
             owner: context.repo.owner,
             repo: context.repo.repo,
             labels: ['build error']
          })

    - name: Resolve build error and add build successful label
      if: ${{ success() && contains(github.event.pull_request.labels.*.name, 'build error') }}
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.removeLabel({
            issue_number: context.payload.pull_request.number,
             owner: context.repo.owner,
             repo: context.repo.repo,
             name: 'build error'
           });
          
           github.rest.issues.addLabels({
             issue_number: context.payload.pull_request.number,
             owner: context.repo.owner,
             repo: context.repo.repo,
             labels: ['build successful']
          })

    - name: Add label build successful to PR
      if: ${{ success() && !contains(github.event.pull_request.labels.*.name, 'build successful') }}
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.addLabels({
            issue_number: context.payload.pull_request.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            labels: ['build successful']
          })

    - name: Add label build error to PR
      if: ${{ failure() }} && !contains(github.event.pull_request.labels.*.name, 'build error') }}
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.addLabels({
            issue_number: context.payload.pull_request.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            labels: ['build error']
          })

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@v3.0.2
